alibaba/dragonwell8_jdk

make/CopyFiles.gmk, make/CreateJars.gmk
Test Plan: existing test cases
Reviewed-by: shiyue, kuaiwei
Issue: https://github.com/alibaba/dragonwell8/issues/52
=> Summary: Disable JFR support in windows/mac build

make/CreateJars.gmk, make/data/classlist/classlist.linux, make/lib/CoreLibraries.gmk, make/mapfiles/libjava/mapfile-vers, make/mapfiles/libjava/reorder-x86, src/share/classes/com/alibaba/jvm/gc/ElasticHeapMXBeanImpl.java, src/share/classes/com/alibaba/management/ElasticHeapEvaluationMode.java, src/share/classes/com/alibaba/management/ElasticHeapMXBean.java, src/share/classes/java/lang/management/PlatformComponent.java, src/share/classes/sun/management/ManagementFactoryHelper.java, src/share/javavm/export/jvm.h, src/share/native/com/alibaba/jvm/gc/ElasticHeapMXBeanImpl.c, test/elastic-heap/TestElasticHeapErrorCode.java, test/elastic-heap/TestElasticHeapMTSetError.java, test/elastic-heap/TestElasticHeapMXBean.java, test/elastic-heap/TestElasticHeapMXBeanException.java
Summary: G1ElasticHeap to support heap shrink/expansion in runtime
Test Plan:
test/elastic-heap/
Reviewers:
Issue:
https://github.com/alibaba/dragonwell8/issues/46
CR:
=> [GC] Port G1ElasticHeap to dragonwell

.github/workflows/check_pr.yml
Summary: added workflow to check pull request
Test Plan: workflow shipped with this PR
Reviewed-by: kuaiwei, sanhong
Issue: https://github.com/alibaba/dragonwell8/issues/80
=> [Misc] Added workflow to check pull request

.github/workflows/check_pr.yml
Summary: add fastdebug workflow in JDK repo to check pull request
Test Plan: workflow shipped with this PR
Reviewed-by: luchsh, yuleil
Issue: alibaba/dragonwell8#82
=> [Misc] Add fastdebug workflow in JDK repo to check pull request

make/CreateJars.gmk, src/share/classes/com/alibaba/rcm/Constraint.java, src/share/classes/com/alibaba/rcm/ResourceContainer.java, src/share/classes/com/alibaba/rcm/ResourceContainerFactory.java, src/share/classes/com/alibaba/rcm/ResourceType.java, src/share/classes/com/alibaba/rcm/internal/AbstractResourceContainer.java, src/share/classes/java/lang/System.java, src/share/classes/java/lang/Thread.java, src/share/classes/sun/misc/JavaLangAccess.java, test/com/alibaba/rcm/TestConfiguration.java, test/com/alibaba/rcm/TestInherit.java, test/com/alibaba/rcm/TestSkeletalAttach.java, test/com/alibaba/rcm/TestState.java, test/com/alibaba/rcm/TestSwitchBetweenContainers.java, test/com/alibaba/rcm/demo/MyResourceContainer.java, test/com/alibaba/rcm/demo/MyResourceFactory.java, test/com/alibaba/rcm/demo/MyResourceType.java
Summary:
Introduce ResourceContainer to manage resources.
ResourceContainer defines a set of resource Constraint
that limit resource usage by threads.
Test Plan: jtreg com/alibaba/rcm
Reviewed-by: luchsh sanhong
Issue: alibaba/dragonwell8#87
=> [Misc] Resource Management API

make/CopyFiles.gmk, make/CreateJars.gmk, make/data/classlist/classlist.linux, make/lib/CoreLibraries.gmk, make/mapfiles/libjava/mapfile-vers, make/mapfiles/libjava/reorder-x86, src/share/classes/com/alibaba/management/TenantContainerMXBean.java, src/share/classes/com/alibaba/tenant/NativeDispatcher.java, src/share/classes/com/alibaba/tenant/TenantConfiguration.java, src/share/classes/com/alibaba/tenant/TenantContainer.java, src/share/classes/com/alibaba/tenant/TenantContainerFactory.java, src/share/classes/com/alibaba/tenant/TenantContainerMXBeanImpl.java, src/share/classes/com/alibaba/tenant/TenantException.java, src/share/classes/com/alibaba/tenant/TenantGlobals.java, src/share/classes/com/alibaba/tenant/TenantResourceContainer.java, src/share/classes/com/alibaba/tenant/TenantResourceType.java, src/share/classes/com/alibaba/tenant/TenantShutdownHooks.java, src/share/classes/com/alibaba/tenant/TenantState.java, src/share/classes/java/lang/Thread.java, src/share/classes/java/lang/management/PlatformComponent.java, src/share/classes/sun/management/ManagementFactoryHelper.java, src/share/javavm/export/jvm.h, src/share/javavm/export/tenantenv.h, src/share/native/com/alibaba/tenant/NativeDispatcher.c, src/share/native/com/alibaba/tenant/TenantGlobals.c, test/lib/testlibrary/jdk/testlibrary/TestUtils.java, test/multi-tenant/test/com/alibaba/tenant/TestTenantContainer.java, test/multi-tenant/test/com/alibaba/tenant/TestTenantContainerFactory.java, test/multi-tenant/test/com/alibaba/tenant/TestTenantGlobals.java
Summary: ported MultiTenant framework to Dragonwell8
Test Plan: jdk/test/multi-tenant
Reviewed-by: yuleil, sanhong
Issue: https://github.com/alibaba/dragonwell8/issues/84
=> [MultiTenant] MultiTenant framework

src/share/classes/com/alibaba/rcm/Constraint.java, src/share/classes/com/alibaba/rcm/ResourceType.java, src/share/classes/com/alibaba/tenant/NativeDispatcher.java, src/share/classes/com/alibaba/tenant/TenantConfiguration.java, src/share/classes/com/alibaba/tenant/TenantContainer.java, src/share/javavm/export/jvm.h, src/share/native/com/alibaba/tenant/NativeDispatcher.c
Summary: ported heap isolation feature of MultiTenant to Dragonwell8
Test Plan: hotspot/test/multi-tenant/{TestHeapIsolation.java,TestMultiTenantOptionDeps.sh,TestPerTenantTLAB.java}
Reviewed-by: luchsh, mmyxym
Issue: https://github.com/alibaba/dragonwell8/issues/90
=> [MultiTenant] Support TenantHeapIsolation

make/CompileLaunchers.gmk, make/CompileNativeLibraries.gmk, make/CopyIntoClasses.gmk, make/CreateJars.gmk, make/Images.gmk, make/lib/JGroupLibraries.gmk, make/mapfiles/libjgroup/mapfile-vers, src/linux/native/jgroup/com/alibaba/tenant/jgroup.c, src/share/classes/com/alibaba/tenant/JGroup.java, src/share/classes/com/alibaba/tenant/JGroupConstraint.java, src/share/classes/com/alibaba/tenant/JGroupInitializer.sh, src/share/classes/com/alibaba/tenant/JGroupMain.java, src/share/classes/com/alibaba/tenant/NativeDispatcher.java, src/share/classes/com/alibaba/tenant/TenantConfiguration.java, src/share/classes/com/alibaba/tenant/TenantContainer.java, src/share/classes/com/alibaba/tenant/TenantResourceContainer.java, src/share/classes/com/alibaba/tenant/TenantResourceType.java, test/multi-tenant/TestGetAllTenantIDs.java, test/multi-tenant/TestJGroupDebugMode.sh, test/multi-tenant/TestNoJGroupInit.java, test/multi-tenant/test/com/alibaba/tenant/TestCpuCfsThrottling.java, test/multi-tenant/test/com/alibaba/tenant/TestHierachicalTenants.java, test/multi-tenant/test/com/alibaba/tenant/TestJGroup.java, test/multi-tenant/test/com/alibaba/tenant/TestJGroupInit.java, test/multi-tenant/test/com/alibaba/tenant/TestTenantConfiguration.java, test/multi-tenant/test/com/alibaba/tenant/TestTenantContainer.java
Summary: ported cgroup-based cpu throttling facilities
Test Plan: jdk/test/multi-tenant
Reviewed-by: yuleil, superajun-wsj
Issue: https://github.com/alibaba/dragonwell8/issues/84
=> [MultiTenant] Added CPU throttling feature

src/share/classes/com/alibaba/tenant/FieldReference.java, src/share/classes/com/alibaba/tenant/TenantContainer.java, src/share/classes/com/alibaba/tenant/TenantData.java, src/share/classes/com/alibaba/tenant/TenantGlobals.java, src/share/classes/java/lang/ClassValue.java, src/share/classes/java/lang/Runtime.java, src/share/classes/java/lang/System.java, src/share/classes/java/lang/management/ManagementFactory.java, src/share/classes/java/lang/ref/Finalizer.java, src/share/classes/java/sql/DriverManager.java, src/share/classes/java/util/ResourceBundle.java, src/share/classes/javax/management/MBeanServerFactory.java, src/share/classes/sun/misc/SharedSecrets.java, src/share/classes/sun/misc/TenantAccess.java, test/multi-tenant/TestStaticFieldIsolation.java, test/multi-tenant/test/com/alibaba/tenant/TestJMX.java
Summary: ported TenantDataIsolation to Dragonwell
Test Plan: jdk/test/multi-tenant
Reviewed-by: yuleil, superajun-wsj
Issue: https://github.com/alibaba/dragonwell8/issues/84
=> [MultiTenant] Added TenantDataIsolation feature

src/share/classes/java/dyn/AsymCoroutine.java, src/share/classes/java/dyn/AsymRunnable.java, src/share/classes/java/dyn/Coroutine.java, src/share/classes/java/dyn/CoroutineBase.java, src/share/classes/java/dyn/CoroutineExitException.java, src/share/classes/java/dyn/CoroutineLocal.java, src/share/classes/java/dyn/CoroutineSupport.java, src/share/classes/java/lang/Thread.java, src/share/classes/sun/misc/VM.java, test/java/dyn/CoroutineTest.java
Summary:
- From http://hg.openjdk.java.net/mlvm/mlvm/jdk/file/93a6c619b0ca/coro-simple.patch
- Add 'EnableCoroutine' option to test/java/dyn/CoroutineTest.java
Test Plan: test/java/dyn/CoroutineTest.java jtreg test
Reviewed-by: yuleil, shiyuexw, sanhong
Issue: https://github.com/alibaba/dragonwell8/issues/113
=> [Coroutine] Import coroutine patch

src/linux/classes/sun/nio/ch/WispSocketImpl.java
Summary:
Refactoring WispSocket's InputStream and OutputStream
creating code for readability.
Test Plan: all wisp tests
Reviewed-by: joeyleeeeeee97 shiyuexw
Issue: alibaba/dragonwell8#124
=> [Wisp] Refactoring WispSocket iostream creation

test/com/alibaba/management/WispCounterMXBean/TestWispCounter.java, test/com/alibaba/wisp/io/BlockingAcceptTest.java, test/com/alibaba/wisp/io/BlockingNIOTest.java, test/com/alibaba/wisp2/bug/PreemptWispInternalBugTest.java
Summary: fix unstable wisp tests
Test Plan: jtreg test/com/alibaba/
Reviewed-by: yuleil, sanhong.lsh
Issue: https://github.com/alibaba/dragonwell8/issues/163
=> [Wisp] Fix intermittent wisp test failure

src/share/classes/com/alibaba/tenant/TenantContainer.java, test/multi-tenant/test/com/alibaba/tenant/TestHierachicalTenants.java, test/multi-tenant/test/com/alibaba/tenant/TestJGroup.java
Summary: fix unstable multi-tenant test failure
Test Plan: jtreg test/com/alibaba/
Reviewed-by: yuleil, yunyao.zxl
Issue: https://github.com/alibaba/dragonwell8/issues/165
=> [MultiTenant] Fix unstable multi-tenant test failure

test/elastic-heap/TestElasticHeapErrorCode.java, test/elastic-heap/TestElasticHeapMTSetError.java, test/elastic-heap/TestElasticHeapMXBean.java, test/elastic-heap/TestElasticHeapMXBeanException.java
Summary: Fix G1ElasticHeap test failures
Test Plan: jtreg tests
Reviewers: Hao Tang, Yude Lin
Issue: https://github.com/alibaba/dragonwell8/issues/177
=> [Misc] Fix G1ElasticHeap test failures

src/linux/classes/com/alibaba/wisp/engine/WispCarrier.java, src/linux/classes/com/alibaba/wisp/engine/WispControlGroup.java, src/linux/classes/com/alibaba/wisp/engine/WispEngine.java, src/linux/classes/com/alibaba/wisp/engine/WispScheduler.java, src/linux/classes/com/alibaba/wisp/engine/WispTask.java, src/share/classes/java/dyn/CoroutineSupport.java, test/com/alibaba/wisp/thread/PreemptTest.java
Summary: Support shutdown by wispControlGroup.
Test Plan: com/alibaba/wisp/thread/PreemptTest.java
Issue: https://github.com/alibaba/dragonwell8/issues/205
=> [Wisp] WispControlGroup shutdown

src/linux/classes/com/alibaba/wisp/engine/WispCarrier.java, src/linux/classes/com/alibaba/wisp/engine/WispTask.java, test/com/alibaba/wisp2/Wisp2ShutdownTest.java
Summary: WispTask memory leak in shutdown.
Test Plan: com/alibaba/wisp/thread/
Issue: https://github.com/alibaba/dragonwell8/issues/211
=> [Wisp] WispTask memory leak in shutdown

src/linux/classes/com/alibaba/wisp/engine/WispTask.java, src/share/classes/java/dyn/Coroutine.java, src/share/classes/java/lang/Thread.java, src/share/classes/sun/management/ThreadImpl.java, test/com/alibaba/wisp/bug/TestThreadStackTrace.sh
This reverts commit 309569b617607463c994b8f11c43bf6960506632.
=> Revert "[Wisp] Support threadMxbean in AllThreadAsWisp"

src/linux/classes/com/alibaba/wisp/engine/WispCarrier.java, src/linux/classes/com/alibaba/wisp/engine/WispControlGroup.java, src/linux/classes/com/alibaba/wisp/engine/WispEngine.java, src/linux/classes/com/alibaba/wisp/engine/WispTask.java, src/share/classes/com/alibaba/management/ResourceContainerMXBean.java, src/share/classes/com/alibaba/rcm/ResourceContainer.java, src/share/classes/com/alibaba/rcm/ResourceContainerMXBeanImpl.java, src/share/classes/com/alibaba/rcm/internal/AbstractResourceContainer.java, src/share/classes/com/alibaba/tenant/TenantResourceContainer.java, test/com/alibaba/rcm/RcmMXBeanTest.java, test/com/alibaba/rcm/demo/MyResourceContainer.java
Summary: reachedLimitCount in ResourceContainerMXBean indicated
how many times this type of resource has reached its limit.
Test Plan: com/alibaba/rcm/
Issue: https://github.com/alibaba/dragonwell8/issues/214
=> [Wisp] Add reachedLimitCount in ResourceContainerMXBean

src/share/classes/jdk/jfr/internal/JVM.java
Summary: Fix compile error in JVM.java
Test Plan: jtreg tests
Reviewed-by: zhengxiaolinX, kelthuzadx
Issue: https://github.com/alibaba/dragonwell8/issues/248
=> [Misc] Fix compile error in JVM.java

src/linux/classes/com/alibaba/wisp/engine/ThreadAsWisp.java, src/linux/classes/com/alibaba/wisp/engine/WispConfiguration.java, test/com/alibaba/wisp2/ThreadAsWispWhiteListTest.java
Summary: Provides a way to run thread as wisp using
configuration
Test Plan: ThreadAsWispWhiteListTest
Reviewed-by: joeylee, zhenxiaolinX
Issue: alibaba/dragonwell8#256
=> [Wisp] Thread as Wisp whitelist

src/linux/classes/com/alibaba/wisp/engine/WispControlGroup.java, src/share/classes/com/alibaba/rcm/ResourceType.java, src/share/classes/com/alibaba/rcm/internal/AbstractResourceContainer.java, src/share/classes/com/alibaba/rcm/internal/ResourceContainerGlobals.java, src/share/classes/com/alibaba/tenant/TenantResourceContainer.java, src/share/classes/java/lang/System.java, test/com/alibaba/rcm/TestPropertyContainerImpls.java, test/com/alibaba/rcm/demo/MyResourceContainer.java
Summary: Generic system property isolation for multi-tenant and wisp
Test Plan: TestPropertyContainerImpls, TestPropertyContainerSkeletal
Reviewed-by: joeyleeeeeee97, sanhong
Issue: alibaba/dragonwell8#274
=> [Misc] System property isolation for RCM

src/share/classes/com/alibaba/rcm/internal/ResourceContainerGlobals.java
Summary: fix LogGeneratedClassesTest
Test Plan: LogGeneratedClassesTest
Reviewed-by: zhengxiaolinX, joeylee.lz
Issue: alibaba/dragonwell8#276
=> [Misc] Use anonymous classes to get RCM config

test/com/alibaba/rcm/RcmCpuTest.java, test/com/alibaba/rcm/RcmRootTest.java, test/com/alibaba/rcm/RcmUpdateTest.java
Summary: fix unstable RCM tests
Test Plan: test/com/alibaba/rcm/
Reviewed-by: zhengxiaolinX, lei.yul
Issue: https://github.com/alibaba/dragonwell8/issues/280
=> [Misc] Fix unstable rcm tests

test/elastic-heap/TestElasticHeapMTSetError.java
Summary: fix unstable elastic-heap tests
Test Plan: jtreg elastic-heap tests
Reviewed-by: Yude Lin, Mao Liang
Issue: https://github.com/alibaba/dragonwell8/issues/288
=> [GC] Fix unstable elastic-heap tests
