alibaba/dragonwell8_jdk

src/share/classes/jdk/jfr/EventNames.java
src/share/classes/jdk/jfr/Recording.java
src/share/classes/jdk/jfr/consumer/RecordedClass.java
src/share/classes/jdk/jfr/internal/JVM.java
src/share/classes/jdk/jfr/internal/Options.java
src/share/classes/jdk/jfr/internal/PlatformRecorder.java
src/share/classes/jdk/jfr/internal/PlatformRecording.java
src/share/classes/jdk/jfr/internal/dcmd/DCmdConfigure.java
src/share/classes/jdk/jfr/internal/dcmd/DCmdStart.java
test/lib/testlibrary/jdk/testlibrary/jfr/EventNames.java

Summary: add support for opto object allocations sampling
Test Plan: hotspot/test/jfr/event/objectsprofiling/TestOptoObjectAllocationsSampling.java
Reviewers: zhengxiaolinX, luchsh, sanhong
Issue: https://github.com/alibaba/dragonwell8/issues/64

[JFR] add support for opto object allocations sampling

---

make/CompileNativeLibraries.gmk
test/multi-tenant/TestGetAllTenantIDs.java
test/multi-tenant/TestJGroupDebugMode.sh
test/multi-tenant/TestNoJGroupInit.java
test/multi-tenant/TestStaticFieldIsolation.java
test/multi-tenant/test/com/alibaba/tenant/TestCpuCfsThrottling.java
test/multi-tenant/test/com/alibaba/tenant/TestHierachicalTenants.java
test/multi-tenant/test/com/alibaba/tenant/TestJGroup.java
test/multi-tenant/test/com/alibaba/tenant/TestJGroupInit.java
test/multi-tenant/test/com/alibaba/tenant/TestJMX.java
test/multi-tenant/test/com/alibaba/tenant/TestTenantConfiguration.java
test/multi-tenant/test/com/alibaba/tenant/TestTenantContainer.java
test/multi-tenant/test/com/alibaba/tenant/TestTenantContainerFactory.java
test/multi-tenant/test/com/alibaba/tenant/TestTenantGlobals.java

Summary: skip jgroup libraries on Windows
Test Plan: jdk/test/multi-tenant
Reviewed-by: kuaiwei, yuleil
Issue: https://github.com/alibaba/dragonwell8/issues/92

[MultiTenant] Fixed build failure on Windows

---

src/share/classes/java/lang/System.java
src/share/classes/java/lang/Thread.java
src/share/classes/sun/misc/JavaLangAccess.java
test/com/alibaba/rcm/TestConfiguration.java
test/com/alibaba/rcm/TestInherit.java
test/com/alibaba/rcm/TestInheritedContainer.java
test/com/alibaba/rcm/TestRootNotNull.java
test/com/alibaba/rcm/demo/RCInheritedThreadFactory.java

Summary:
- Replace null with root() to represent root container for consistency
- Support rcm inheritance by Thread.inheritedResourceContainer
Test Plan: jtreg com/alibaba/rcm/ multi-tenent/
Reviewed-by: luchsh
Issue: https://github.com/alibaba/dragonwell8/issues/95

[Misc] Polish rcm API

---

src/share/classes/jdk/jfr/EventNames.java
src/share/classes/jdk/jfr/Recording.java
src/share/classes/jdk/jfr/conf/default.jfc
src/share/classes/jdk/jfr/conf/profile.jfc
src/share/classes/jdk/jfr/consumer/RecordedClass.java
src/share/classes/jdk/jfr/internal/JVM.java
src/share/classes/jdk/jfr/internal/Options.java
src/share/classes/jdk/jfr/internal/PlatformRecorder.java
src/share/classes/jdk/jfr/internal/PlatformRecording.java
src/share/classes/jdk/jfr/internal/dcmd/DCmdConfigure.java
src/share/classes/jdk/jfr/internal/dcmd/DCmdStart.java
test/jdk/jfr/event/objectsprofiling/TestOptoObjectAllocationsSampling.java
test/lib/jdk/test/lib/jfr/EventNames.java

This reverts commit 98c962d63491fd35e74174f96a2e5da26c63f13d.

Revert "Revert "[JFR] add support for opto object allocations sampling""

---

src/share/classes/jdk/jfr/conf/default.jfc
src/share/classes/jdk/jfr/conf/profile.jfc
test/jdk/jfr/event/compiler/TestHugeObjectAllocationSample.java
test/jdk/jfr/event/metadata/TestLookForUntestedEvents.java
test/jdk/jfr/event/runtime/TestSafepointEvents.java
test/lib/jdk/test/lib/jfr/EventNames.java

Summary:
SafepointStatistics is a periodic event, both events are experimental
now and disbaled by default
Test Plan:
jdk/jfr/event/runtime/TestSafepointEvents.java
jdk/jfr/event/compiler/TestHugeObjectAllocationSample.java
jdk/jfr/event/metadata/TestLookForUntestedEvents.java
Reviewed-by: kuaiwei
Issue: https://github.com/alibaba/dragonwell8/issues/116

[JFR] Added SafepointStatistics and HugeObjectAllocationSample Events

---

src/macosx/classes/com/alibaba/wisp/engine/WispCounter.java
src/macosx/classes/com/alibaba/wisp/engine/WispCounterMXBeanImpl.java
src/windows/classes/com/alibaba/wisp/engine/WispCounter.java
src/windows/classes/com/alibaba/wisp/engine/WispCounterMXBeanImpl.java

Summary: as the title
Test Plan: On Windows platform: TestAggressiveHeap.java, TestExcessGCLockerCollections.java and ThreadCpuTimesDeadlock.java
Reviewed-by: yuleil, shiyuexw
Issue: https://github.com/alibaba/dragonwell8/issues/113

[Wisp] Fix Windows compatibility issue by adding dummy getX methods

---

test/com/sun/jdi/TestScaffold.java

Summary: Alibaba's breakpoint needs to be skipped for StepTest.java, otherwise we may enter an unexpected break position.
Reviewed-by: DDH, yuleil
Issue: https://github.com/alibaba/dragonwell8/issues/111

[Misc] fix failed test com/sun/jdi/StepTest.java

---

test/com/sun/jdi/SimulResumerTest.java

Summary: Backport of 6815126, array length varies in jdi test
Test Plan: test/com/sun/jdi/SimulResumerTest.java
Reviewed-by: yuleil, DDH
Issue: https://github.com/alibaba/dragonwell8/issues/129

[Backport] fix intermittent SimulResumerTest.java failure

---

src/linux/classes/sun/nio/ch/WispSocketImpl.java
test/com/alibaba/wisp2/Wisp2SocketCloseExceptionTest.java

Summary:
Make the behavior of reading a closed socket to be consistent
after switching wisp.
Test Plan: Wisp2SocketCloseExceptionTest
Reviewed-by: joeyleeeeeee97 shiyuexw
Issue: alibaba/dragonwell8#124

[Wisp] Fix unexpected socket closed exception

---

src/share/classes/jdk/jfr/conf/default.jfc
src/share/classes/jdk/jfr/conf/profile.jfc
test/jdk/jfr/event/runtime/TestThreadStartEndEvents.java

Summary:
Test Plan: test/jdk/jfr/event/runtime/TestThreadStartEndEvents.java
Reviewed-by: zhengxiaolinX, yuleil
Issue: https://github.com/alibaba/dragonwell8/issues/127

[Backport] 8237499: JFR: Include stack trace in the ThreadStart event

---

src/linux/classes/com/alibaba/wisp/engine/WispTask.java
src/share/classes/java/dyn/Coroutine.java
src/share/classes/java/lang/Thread.java
src/share/classes/sun/management/ThreadImpl.java
test/com/alibaba/wisp/bug/TestThreadStackTrace.sh
test/com/alibaba/wisp2/WispThreadMXBeanTest.java

Summary: Support ThreadMxBean to inspect coroutine
infomation, including getThreadInfo, dumpAllThreads,
getThreadCount, getAllThreadIds.
Test Plan: com/alibaba/wisp2/WispThreadMXBeanTest.java
Reviewed-by: zhengxiaolinX, yuleil, sanhongli
Issue: https://github.com/alibaba/dragonwell8/issues/132

[Wisp] Support threadMxbean in AllThreadAsWisp

---

src/linux/classes/com/alibaba/wisp/engine/WispCarrier.java
src/linux/classes/com/alibaba/wisp/engine/WispEngine.java
src/linux/classes/com/alibaba/wisp/engine/WispTask.java
src/share/classes/sun/management/ThreadImpl.java
src/share/classes/sun/misc/WispEngineAccess.java
test/com/alibaba/wisp2/WispThreadMXBeanTest.java

Summary: Add profile info for all thread converted coroutines,
supporting ThreadMXBean interfaces such as getCpuTime.
Test Plan: com/alibaba/wisp2/WispThreadMXBeanTest.java
Reviewed-by: zhengxiaolinX, yuleil, sanhongli
Issue: https://github.com/alibaba/dragonwell8/issues/136

[Wisp] Get CPU time in threadMxbean

---

src/macosx/classes/com/alibaba/wisp/engine/WispEngine.java
src/windows/classes/com/alibaba/wisp/engine/WispEngine.java

Summary: Add pseudo getCPUTime in WispEngine on macosx&windows
to fix compile error
Test Plan: windows sanity jtreg test set.
Reviewed-by: zhengxiaolinX, yuleil
Issue: https://github.com/alibaba/dragonwell8/issues/142

[Wisp] Add pseudo getCPUTime in WispEngine on macosx&windows

---

src/linux/classes/com/alibaba/wisp/engine/WispEngine.java
src/macosx/classes/com/alibaba/wisp/engine/WispEngine.java
src/share/classes/java/nio/channels/spi/AbstractSelectableChannel.java
src/share/classes/sun/misc/WispEngineAccess.java
src/share/classes/sun/nio/ch/IOStatus.java
src/share/classes/sun/nio/ch/ServerSocketChannelImpl.java
src/share/classes/sun/nio/ch/SocketChannelImpl.java
src/solaris/classes/sun/nio/ch/SinkChannelImpl.java
src/solaris/classes/sun/nio/ch/SourceChannelImpl.java
src/windows/classes/com/alibaba/wisp/engine/WispEngine.java
test/com/alibaba/wisp/io/BlockingNIOTest.java

Summary: Hook blocking entry at pipeChannel and SocketChannel,
current WispTask would block itself to wait for next scheduling.
Test Plan: jtreg BlockIngIOTest.
Reviewed-by: zhengxiaolinX, yuleil
Issue: https://github.com/alibaba/dragonwell8/issues/143

[Wisp] Blocking io support for SocketChannel and Pipe

---

src/share/classes/sun/nio/ch/SelectorImpl.java

Summary:
Revert changes since we do not use NIO as a part of WispEngine.
This reverts commit c6b1deec0b72f858723e0d328599a138da250c10.
Test Plan: Run all jtreg tests
Reviewed-by: yuleil, zhengxiaolinX
Issue: https://github.com/alibaba/dragonwell8/issues/175

[Wisp] Revert "Fix NIO deadlock"

---

src/linux/classes/com/alibaba/wisp/engine/WispTask.java
test/com/alibaba/wisp2/WispUncaughtExceptionTest.java

Summary:
Dispatch thread uncaught exception to the UncaughtExceptionHandler.
Test Plan: WispUncaughtTest
Reviewed-by: zhengxiaolinX, sanhong.lsh
Issue: https://github.com/alibaba/dragonwell8/issues/174

[Wisp] handle thread uncaught exception

---

src/windows/classes/com/alibaba/wisp/engine/WispThreadWrapper.java

Summary: Delete the getCoroutineSupport method
from the windows directory.
Test Plan: build
Reviewed-by: joeyleeeeeee97, D-D-H
Issue: alibaba/dragonwell8#198

[Wisp] Fix windows build failure

---

src/linux/classes/com/alibaba/wisp/engine/WispCarrier.java
src/linux/classes/com/alibaba/wisp/engine/WispConfiguration.java
src/linux/classes/com/alibaba/wisp/engine/WispTask.java
src/share/classes/java/dyn/CoroutineBase.java
src/share/classes/java/dyn/CoroutineSupport.java
test/com/alibaba/wisp2/NmtTracingWispTaskRecycleTest.java
test/com/alibaba/wisp2/ReleaseWispTaskTest.java
test/com/alibaba/wisp2/WispUncaughtExceptionTest.java

Summary:
Setting an upper limit of cache space for exited wisp tasks, and release
uncached wisp tasks' memory resources, especially stack memory resources.
Test Plan:
test/com/alibaba/wisp2/NmtTracingWispTaskRecycleTest.java,
test/com/alibaba/wisp2/ReleaseWispTaskTest.java.
Reviewed-by: lei.yul, sanhong.lsh, joeylee.lz
Issue: https://github.com/alibaba/dragonwell8/issues/170

[Wisp] release uncached wisp task and coroutine stack resource

---

src/linux/classes/com/alibaba/wisp/engine/WispCarrier.java
test/com/alibaba/wisp2/TestEpollArrayClear.java

Summary: In wisp Monolithic Epoll, we clear Epoll fd after the park.
But at shutdown, an interruption may break this and leave an uncleared
epoll array on wise task, IllegalArgumentException may happen when reuse
this wispTask.
Test Plan: jtreg test/wisp2
Reviewed-by: yuleil, zhengxiaolinX
Issue: https://github.com/alibaba/dragonwell8/issues/208

[Wisp] Fix WispEventPump epollWait IllegalArgumentException

---

src/linux/classes/com/alibaba/wisp/engine/WispCarrier.java
test/com/alibaba/rcm/RcmMXBeanTest.java

Summary: use WispCarrier.current() to check shutdown
rather than object local field, because field variable
may change during coroutine stealing.
Test Plan: com/alibaba/rcm/
Issue: https://github.com/alibaba/dragonwell8/issues/214

[Wisp] Use current carrier to check shutdown

---

src/linux/classes/com/alibaba/wisp/engine/WispTask.java
test/com/alibaba/wisp/bug/LazySetUnparkTest.java

Summary: In wisp1 we use direct scheduler wakeup instead
of park/unpark for coroutine timed-waiting, so for historical
reason exists a manual status fix to lazy set status to free.
But in wisp2 when timer is waken up by unpark, a PERMITTED
may be overwriten and cause problem.
Test Plan: com/alibaba/rcm/
Reviewed-by: leiyu, zhengxiaolinX, sanhong.lsh
Issue: https://github.com/alibaba/dragonwell8/issues/236

[Wisp] Fix overwrite PERMITTED status in lazySet

---

src/share/classes/com/alibaba/rcm/ResourceContainerMXBeanImpl.java
src/share/classes/com/alibaba/rcm/internal/AbstractResourceContainer.java
test/com/alibaba/rcm/RcmMXBeanTest.java
test/com/alibaba/rcm/RcmUtils.java

Summary: Get all active threads from root container.
Test Plan: com/alibaba/rcm/
Reviewed-by: leiyu, sanhong.lsh
Issue: https://github.com/alibaba/dragonwell8/issues/237

[Wisp] Get active thread ids from root container

---

src/share/classes/java/lang/Thread.java
test/com/alibaba/wisp/bug/ThreadSelfInterrupt.java

Summary: Self interrupt may hang forever without 8198841.
Backport 8198841 for self interrupt wisp coroutines.
https://bugs.openjdk.java.net/browse/JDK-8198841
Test Plan: com/alibaba/wisp/bug/ThreadSelfInterrupt
Issue: https://github.com/alibaba/dragonwell8/issues/239

[Wisp] Skip Interruptible when current thread interrupting itself

---

src/linux/classes/com/alibaba/wisp/engine/TaskDispatcher.java
src/linux/classes/com/alibaba/wisp/engine/ThreadAsWisp.java
src/linux/classes/com/alibaba/wisp/engine/WispCarrier.java
src/linux/classes/com/alibaba/wisp/engine/WispEngine.java
src/linux/classes/com/alibaba/wisp/engine/WispTask.java
src/macosx/classes/com/alibaba/wisp/engine/WispEngine.java
src/share/classes/java/lang/Thread.java
src/share/classes/sun/misc/WispEngineAccess.java
src/windows/classes/com/alibaba/wisp/engine/WispEngine.java
test/com/alibaba/wisp2/Wisp2StackSizeTest.java

Summary:
Previously wisp uses 512k as the stack size and ignores `Thread.stackSize`.
This PR will make wisp to use `Thread.stackSize` as its stack size.
Test Plan: com/alibaba/wisp2/
Reviewed-by: joeyleeeeeee97, yuleil
Issue: alibaba/dragonwell8#240

[Wisp] Adapt `Thread.stackSize`

---

src/linux/classes/com/alibaba/wisp/engine/WispCarrier.java

Summary: re-wakeup a exited coroutine can waste a lot of CPU
Test Plan: Verify on a reproducible environment
Reviewed-by: joeylee, zhenxiaolinX
Issue: alibaba/dragonwell8#262

[Wisp] Exited coroutine should not be re-wakeuped

---

test/tools/launcher/VersionCheck.java

Summary: Exclude jgroup version output when enumerating bin dir.
Test Plan: CI pipeline
Reviewed-by: zhengxiaolinX, D-D-H
Issue: alibaba/dragonwell8#273

[Misc] Fix unstable VersionCheck test

---

src/share/classes/jdk/jfr/consumer/EventStream.java
src/share/classes/jdk/jfr/consumer/RecordingStream.java
src/share/classes/jdk/jfr/internal/consumer/AbstractEventStream.java

Summary: For maintainability and compatibility, deprecate JFR
Streaming public API, and will revert related backports in the next GA.
Test Plan: jfr tests
Reviewed-by: kelthuzadx, zhengxiaolinX, yuleil
Issue: https://github.com/alibaba/dragonwell8/issues/275

[JFR] Deprecate public JFR Streaming API

---

src/linux/classes/com/alibaba/wisp/engine/WispTask.java
test/com/alibaba/wisp2/bug/ThreadGroupLockTest.java

Summary:
Before Thread.exit() completes, WispTask.isAlive() should be true.
Otherwise, any yieldTo will fail and cause the coroutine fail to exit.
Test Plan: Verify in the production environment & ThreadGroupLockTest
Reviewed-by: zhengxiaolinX, joeylee.lz, sanhong
Issue: alibaba/dragonwell8#278

[Wisp] fix wisp block on Thread.exit() infinitely

---

src/linux/classes/com/alibaba/wisp/engine/WispEngine.java
test/com/alibaba/wisp2/WispControlGroupCpuTest.java

Summary:
- Pre-load switch table class in TimeOut::doAction
- Add warmup for WispControlGroupCpuTest
Test Plan: jtreg jdk/test/com/alibaba/wisp{,2}
Reviewed-by: zhengxiaolinX, joeylee.lz
Issue: alibaba/dragonwell8#279

[Wisp] fix LoadClassInnerWispGuard and WispControlGroupCpuTest

---

test/com/alibaba/wisp/monitor/PassTokenTest.java

Summary: There is an unlocked time window between pass token and notify
next, causing the test to occasionally fail.
Test Plan: PassTokenTest
Reviewed-by: D-D-H, joeylee97
Issue: alibaba/dragonwell8#290

[Wisp] Fix PassTokenTest
